language: php
matrix:
  include:
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: 5.4

install:
  - sudo apt-get install p7zip-full
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"

  # install composer dependencies
  - travis_retry composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install

  - composer require --no-interaction gemorroj/archive7z phpclasses/php-iso-file pear/archive_tar

script:
  # PHP tests
  - vendor/bin/phpunit --verbose
